@PORT = 3000
@HOST = http://localhost:{{PORT}}


### Get Users
GET {{HOST}}/api/users

### Get User by Id
GET {{HOST}}/api/users/2

### Register User
POST {{HOST}}/api/auth/register
Content-Type: application/json

{
    "password": "password",
    "name": "UserName",
    "email": "name@gmail.com"
}

### Login User
POST {{HOST}}/api/auth/login
Content-Type: application/json

{
    "email": "name@gmail.com",
    "password": "password"
}


### Get Groups
GET {{HOST}}/api/groups

### Get Groups by Id
GET {{HOST}}/api/groups/2

### Get Groups by Creator_id
GET {{HOST}}/api/groups/creator_id/1

### Create Group
POST {{HOST}}/api/groups
Content-Type: application/json

{
    "creator_id" : "1",
    "title" : "Grupo de prueba gasto desde peticiones",
    "description" : "creado desde peticiones para hacer pruebas, repartir gastos, añadir, etc",
    "image_url" : "/images/grupo1_pruebas"
}
