@PORT = 3000
@HOST = http://localhost:{{PORT}}


### Get Users
GET {{HOST}}/api/users

### Get User by Id
GET {{HOST}}/api/users/2

### Register User
POST {{HOST}}/api/users/register
Content-Type : application/json

{
    "password" : "98765",
    "name" : "Elena",
    "email" : "met@gmail.com",
    "image_url" : "image/elena.jpg",
    "state" : "Active"
}


### Login User
POST {{HOST}}/api/users/login
Content-Type: application/json

{
    "email" : "met@gmail.com",
    "password" : "98765"
}


### Get Groups
GET {{HOST}}/api/groups

### Get Groups by Id
GET {{HOST}}/api/groups/2

### Get Groups by Creator_id
GET {{HOST}}/api/groups/creator_id/1

### Create Group
POST {{HOST}}/api/groups
Content-Type: application/json

{
    "creator_id" : "1",
    "title" : "Grupo de prueba gasto desde peticiones",
    "description" : "creado desde peticiones para hacer pruebas, repartir gastos, añadir, etc",
    "image_url" : "/images/grupo1_pruebas"
}
